### ISSUE TITLE
Sudo permissions are required to set up the resolver

### ISSUE THREAD

**Issue by FleetAdmiralButter** [yusufhm/rockpool#2]
It appears Rockpool needs to write to /etc/resolver to set up the local DNS resolver.

This directory is owned by root, so running Rockpool as a regular user will throw a write error:

```
[rockpool] creating resolver file
panic: exit status 1

goroutine 1 [running]:
github.com/yusufhm/rockpool/pkg/rockpool.(*Rockpool).InstallResolver(0x1006e8000)
	/home/runner/work/rockpool/rockpool/pkg/rockpool/rockpool.go:314 +0x278
github.com/yusufhm/rockpool/pkg/rockpool.(*Rockpool).SetupLagoonController(0x1006e8000)
	/home/runner/work/rockpool/rockpool/pkg/rockpool/rockpool.go:136 +0xa4
github.com/yusufhm/rockpool/pkg/rockpool.(*Rockpool).Up(0x1006e8000, {0x10071e708, 0x0, 0x0})
	/home/runner/work/rockpool/rockpool/pkg/rockpool/rockpool.go:49 +0x554
github.com/yusufhm/rockpool/cmd.glob..func2(0x1006e8680, {0x10071e708, 0x0, 0x0})
	/home/runner/work/rockpool/rockpool/cmd/root.go:42 +0x88
github.com/spf13/cobra.(*Command).execute(0x1006e8680, {0x10071e708, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x1006e8400)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/yusufhm/rockpool/cmd.Execute()
	/home/runner/work/rockpool/rockpool/cmd/root.go:148 +0x30
main.main()

```

**Comment by FleetAdmiralButter** [comment]
Running the binary as sudo turns out to be a bad idea and will mess up the config file permissions....

Workaround by running `sudo chown -R $USER /etc/resolver/rockpool.k3d.local`

**Comment by yusufhm** [comment]
Thanks for this one @FleetAdmiralButter; for some reason mine didn't ask for permissions. I wonder if that's not just the same as #1, but it's `panic`king without the correct error.
